modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/TwistedGate/ImmersivePosts/issues"
license="TwistedGate's License of Common Sense (A modified copy of \"Blu's License of Common Sense\")"

[[mods]]
	displayName="Immersive Posts"
	modId="immersiveposts"
	version="${ipo_version}"
	logoFile= "../logo.png"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/immersiveposts"
	updateJSONURL="https://raw.githubusercontent.com/TwistedGate/ImmersivePosts/master/change.json"
	credits='''§nInspired by ImmersiveIntegration's extendable posts.§r

§l§2--- Translations ---§r
Russian: Shellyoung
Chinese: scikirbypoke, kappa-maintainer
Spanish: FrannDzs
Korean : FreddyYj'''
	authors="TwistedGate"
	description="Simply adds a way to have extendable posts. With a few post types to choose from."

[[dependencies.immersiveposts]]
	modId="immersiveengineering"
	type="required"
	versionRange="[${ie_version},)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.immersiveposts]]
	modId="neoforge"
	type="required"
	versionRange="[${neo_version},)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersiveposts]]
	modId="minecraft"
	type="required"
	versionRange="[${mc_version}]"
	ordering="NONE"
	side="BOTH"
